{
  "formatVersion": "1.1",
  "component": {
    "group": "kr.co.pointclick.sdk.offerwall",
    "module": "pointclick-sdk-offerwall",
    "version": "1.1.07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "pointclick-sdk-offerwall-1.1.07.aar",
          "url": "pointclick-sdk-offerwall-1.1.07.aar",
          "size": 2617852,
          "sha512": "c27b65fc575385df8b3ffe3f75bfe24bcf285c2360d4b1795a2eda9fbedccbd1c0a8cc88ba2fb483852a0467904eb28393f52aff8e35e3bba7f8680b65337d9d",
          "sha256": "3f364b76dbd96cdb984cdce23362a7a9a39e6ccf0002e32f02df949ec3b2dfaa",
          "sha1": "0d7de625ed313d037c9e893719f254d1f468b84c",
          "md5": "0225f635211edbc9199af66b94574688"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-recyclerview-v7",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview-selection",
          "version": {
            "requires": "1.1.0-rc03"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.71828"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-rxjava2-adapter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.1.0"
          }
        },
        {
          "group": "com.github.hannesa2",
          "module": "AndroidSlidingUpPanel",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "com.makeramen",
          "module": "roundedimageview",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "adquality-sdk",
          "version": {
            "requires": "7.26.2"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "applovin-adapter",
          "version": {
            "requires": "4.3.50"
          }
        },
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "13.1.0"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "bidmachine-adapter",
          "version": {
            "requires": "4.3.11"
          }
        },
        {
          "group": "io.bidmachine",
          "module": "ads",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "fyber-adapter",
          "version": {
            "requires": "4.3.37"
          }
        },
        {
          "group": "com.fyber",
          "module": "marketplace-sdk",
          "version": {
            "requires": "8.3.6"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "facebook-adapter",
          "version": {
            "requires": "4.3.48"
          }
        },
        {
          "group": "com.facebook.android",
          "module": "audience-network-sdk",
          "version": {
            "requires": "6.18.0"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "inmobi-adapter",
          "version": {
            "requires": "4.3.32"
          }
        },
        {
          "group": "com.inmobi.monetization",
          "module": "inmobi-ads-kotlin",
          "version": {
            "requires": "10.8.7"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "vungle-adapter",
          "version": {
            "requires": "4.3.29"
          }
        },
        {
          "group": "com.vungle",
          "module": "vungle-ads",
          "version": {
            "requires": "7.4.3"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "mintegral-adapter",
          "version": {
            "requires": "4.3.36"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "mbridge_android_sdk",
          "version": {
            "requires": "16.9.41"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "moloco-adapter",
          "version": {
            "requires": "4.3.12"
          }
        },
        {
          "group": "com.moloco.sdk",
          "module": "moloco-sdk",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "pangle-adapter",
          "version": {
            "requires": "4.3.35"
          }
        },
        {
          "group": "com.pangle.global",
          "module": "ads-sdk",
          "version": {
            "requires": "6.5.0.3"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "smaato-adapter",
          "version": {
            "requires": "4.3.14"
          }
        },
        {
          "group": "com.smaato.android.sdk",
          "module": "smaato-sdk-banner",
          "version": {
            "requires": "22.7.2"
          }
        },
        {
          "group": "com.smaato.android.sdk",
          "module": "smaato-sdk-in-app-bidding",
          "version": {
            "requires": "22.7.2"
          }
        },
        {
          "group": "com.smaato.android.sdk",
          "module": "smaato-sdk-interstitial",
          "version": {
            "requires": "22.7.2"
          }
        },
        {
          "group": "com.smaato.android.sdk",
          "module": "smaato-sdk-rewarded-ads",
          "version": {
            "requires": "22.7.2"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "unityads-adapter",
          "version": {
            "requires": "4.3.49"
          }
        },
        {
          "group": "com.unity3d.ads",
          "module": "unity-ads",
          "version": {
            "requires": "4.13.1"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "verve-adapter",
          "version": {
            "requires": "4.3.4"
          }
        },
        {
          "group": "net.pubnative",
          "module": "hybid.sdk",
          "version": {
            "requires": "3.2.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-basement",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "pointclick-sdk-offerwall-1.1.07.aar",
          "url": "pointclick-sdk-offerwall-1.1.07.aar",
          "size": 2617852,
          "sha512": "c27b65fc575385df8b3ffe3f75bfe24bcf285c2360d4b1795a2eda9fbedccbd1c0a8cc88ba2fb483852a0467904eb28393f52aff8e35e3bba7f8680b65337d9d",
          "sha256": "3f364b76dbd96cdb984cdce23362a7a9a39e6ccf0002e32f02df949ec3b2dfaa",
          "sha1": "0d7de625ed313d037c9e893719f254d1f468b84c",
          "md5": "0225f635211edbc9199af66b94574688"
        }
      ]
    }
  ]
}
