{
  "formatVersion": "1.1",
  "component": {
    "group": "kr.co.pointclick.sdk.offerwall",
    "module": "pointclick-sdk-offerwall",
    "version": "1.1.06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "pointclick-sdk-offerwall-1.1.06.aar",
          "url": "pointclick-sdk-offerwall-1.1.06.aar",
          "size": 2599452,
          "sha512": "937b609549a2b7ca5daca5311e611a8cfca480991c8a2786caca00c5ba159a70906859574ff05e9e2f6609b5a4e949b070e3e3a2439c44ba9bfd18017856a508",
          "sha256": "0334ab994d6bf6bc23ca2aa737b03f609bc29354d3aa6f1f6089525c9329167a",
          "sha1": "47f3c2526394686e6ea0784a051cb32a4fe3f4f2",
          "md5": "8488f8b465b52ee0591b87d51deba7c8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-recyclerview-v7",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview-selection",
          "version": {
            "requires": "1.1.0-rc03"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.71828"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-rxjava2-adapter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.1.0"
          }
        },
        {
          "group": "com.github.hannesa2",
          "module": "AndroidSlidingUpPanel",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "com.makeramen",
          "module": "roundedimageview",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "pointclick-sdk-offerwall-1.1.06.aar",
          "url": "pointclick-sdk-offerwall-1.1.06.aar",
          "size": 2599452,
          "sha512": "937b609549a2b7ca5daca5311e611a8cfca480991c8a2786caca00c5ba159a70906859574ff05e9e2f6609b5a4e949b070e3e3a2439c44ba9bfd18017856a508",
          "sha256": "0334ab994d6bf6bc23ca2aa737b03f609bc29354d3aa6f1f6089525c9329167a",
          "sha1": "47f3c2526394686e6ea0784a051cb32a4fe3f4f2",
          "md5": "8488f8b465b52ee0591b87d51deba7c8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pointclick-sdk-offerwall-1.1.06-sources.jar",
          "url": "pointclick-sdk-offerwall-1.1.06-sources.jar",
          "size": 144528,
          "sha512": "4c094ba192f89ef5cf86ef48a51e635e102a1733d5e640034f8ce7e935d3314c5c229a47cdf953571f4bcd87d7751657eb074cda842b289b31b27e11fef826f8",
          "sha256": "5d96cc13400e20df147399a4a7f7feba1ef25fe57ab8116e2e7ad9be7dd66f0e",
          "sha1": "7667bc408a134527debfea9e12d35e4883876f72",
          "md5": "09292227d15ce8cace9f10858f24851e"
        }
      ]
    }
  ]
}
