{
  "formatVersion": "1.1",
  "component": {
    "group": "kr.co.pointclick.sdk.offerwall",
    "module": "pointclick-sdk-offerwall-test",
    "version": "1.1.06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "pointclick-sdk-offerwall-test-1.1.06.aar",
          "url": "pointclick-sdk-offerwall-test-1.1.06.aar",
          "size": 2602679,
          "sha512": "680ba3b34eb5c1b3a1dd440fe309c4a74e928e9285eefbfed33da209f84fe8b687bbaf52e877f7a8f33c99e282c8ef10bd51a623828ec59814b54397f91a1d63",
          "sha256": "ae721d71a5385d033397774b7edd1916df8508396a5d34b22de30402fd3436ee",
          "sha1": "1d7a13cd81d0f1b8767ee7c68d59375967e98937",
          "md5": "f7e6b8a788759da4988ae0269cd5ccce"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-recyclerview-v7",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview-selection",
          "version": {
            "requires": "1.1.0-rc03"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.71828"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-rxjava2-adapter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.1.0"
          }
        },
        {
          "group": "com.github.hannesa2",
          "module": "AndroidSlidingUpPanel",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "com.makeramen",
          "module": "roundedimageview",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "pointclick-sdk-offerwall-test-1.1.06.aar",
          "url": "pointclick-sdk-offerwall-test-1.1.06.aar",
          "size": 2602679,
          "sha512": "680ba3b34eb5c1b3a1dd440fe309c4a74e928e9285eefbfed33da209f84fe8b687bbaf52e877f7a8f33c99e282c8ef10bd51a623828ec59814b54397f91a1d63",
          "sha256": "ae721d71a5385d033397774b7edd1916df8508396a5d34b22de30402fd3436ee",
          "sha1": "1d7a13cd81d0f1b8767ee7c68d59375967e98937",
          "md5": "f7e6b8a788759da4988ae0269cd5ccce"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "pointclick-sdk-offerwall-test-1.1.06-sources.jar",
          "url": "pointclick-sdk-offerwall-test-1.1.06-sources.jar",
          "size": 147317,
          "sha512": "af8779608d1642441eea92d19e790fe544f96770c15453d89f66fae268870f3445d9dd1397e9b6399cd7936543008b17a23b7a5ad5d28f424ca225ab7ba7ac13",
          "sha256": "8dd208262d9b1c03a5741023b9323c14e3a24e3cf7977d27823f5dcaa2a64a14",
          "sha1": "c2fd1d22b07d8bfb89a1783d4f42895af19b68e2",
          "md5": "c80b3b27150b6ae7680b2aeb8bd2b98a"
        }
      ]
    }
  ]
}
