{
  "formatVersion": "1.1",
  "component": {
    "group": "kr.co.pointclick.sdk.offerwall",
    "module": "pointclick-sdk-offerwall",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pointclick-sdk-offerwall-1.0.5.aar",
          "url": "pointclick-sdk-offerwall-1.0.5.aar",
          "size": 1357940,
          "sha512": "86e36a0452ea654a8d061665cb2c61abb80fa9d5dfead4d4206c4343db03d79f96e8d11fb796e78f3d6e33ed449bec9e3523b74e2dafeb7d45750c202944d929",
          "sha256": "a213a98bf85ffd46148e2a387d1fbd05518aa897ca634911f18bb2f1fa2c5f56",
          "sha1": "5d610bf2a3fb0154eb250851075d25ac25739cf0",
          "md5": "3696ca1ce67db6ee1239a685de49de8e"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-recyclerview-v7",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview-selection",
          "version": {
            "requires": "1.1.0-rc03"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.71828"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-rxjava2-adapter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.1.0"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "pointclick-sdk-offerwall-1.0.5.aar",
          "url": "pointclick-sdk-offerwall-1.0.5.aar",
          "size": 1357940,
          "sha512": "86e36a0452ea654a8d061665cb2c61abb80fa9d5dfead4d4206c4343db03d79f96e8d11fb796e78f3d6e33ed449bec9e3523b74e2dafeb7d45750c202944d929",
          "sha256": "a213a98bf85ffd46148e2a387d1fbd05518aa897ca634911f18bb2f1fa2c5f56",
          "sha1": "5d610bf2a3fb0154eb250851075d25ac25739cf0",
          "md5": "3696ca1ce67db6ee1239a685de49de8e"
        }
      ]
    }
  ]
}
