{
  "formatVersion": "1.1",
  "component": {
    "group": "kr.co.pointclick.sdk.offerwall",
    "module": "pointclick-sdk-offerwall",
    "version": "1.0.7",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "pointclick-sdk-offerwall-1.0.7.aar",
          "url": "pointclick-sdk-offerwall-1.0.7.aar",
          "size": 1358069,
          "sha512": "2ffe9b73cb96b7b6bc407f67c12d622e175c6771293d8cbad37f610405dd96bd679d4b4290b0b042020e3953305e12c0dbcbe8c8b8778b6d57f494799e42c42a",
          "sha256": "f0e6871310b34e5fdebdd5c6997b3534d2e9a54a06fb460053b28856fc8fac34",
          "sha1": "cda427ae99bed0dc779940855b21424e0ad32001",
          "md5": "b2f1b88521272f2a1bfd09149c954535"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxandroid",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "io.reactivex.rxjava3",
          "module": "rxjava",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-recyclerview-v7",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview-selection",
          "version": {
            "requires": "1.1.0-rc03"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.71828"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-rxjava2-adapter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.1.0"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "pointclick-sdk-offerwall-1.0.7.aar",
          "url": "pointclick-sdk-offerwall-1.0.7.aar",
          "size": 1358069,
          "sha512": "2ffe9b73cb96b7b6bc407f67c12d622e175c6771293d8cbad37f610405dd96bd679d4b4290b0b042020e3953305e12c0dbcbe8c8b8778b6d57f494799e42c42a",
          "sha256": "f0e6871310b34e5fdebdd5c6997b3534d2e9a54a06fb460053b28856fc8fac34",
          "sha1": "cda427ae99bed0dc779940855b21424e0ad32001",
          "md5": "b2f1b88521272f2a1bfd09149c954535"
        }
      ]
    }
  ]
}
