{
  "formatVersion": "1.1",
  "component": {
    "group": "kr.co.pointclick.sdk.offerwall",
    "module": "pointclick-sdk-offerwall-test",
    "version": "1.1.07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "pointclick-sdk-offerwall-test-1.1.07.aar",
          "url": "pointclick-sdk-offerwall-test-1.1.07.aar",
          "size": 2633203,
          "sha512": "25b90451f15798ea37ad62b00a4aafa0527c736c39b526db88bfd89998a143cec3fb95efbe80fb3488d650d693e6ba6abe0feb10f566afbaa4fccc6bf04ebd0a",
          "sha256": "1cef75f4190c0c362102100d1a1b20e4cfe5b7e5ef657cf94a83f255fc23fae7",
          "sha1": "9470820f6b1903319b6ac401dbe16cfc692b58ec",
          "md5": "b3fc0689fb89ca729a707e6e307d5ea0"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-recyclerview-v7",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview-selection",
          "version": {
            "requires": "1.1.0-rc03"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.71828"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-rxjava2-adapter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.1.0"
          }
        },
        {
          "group": "com.github.hannesa2",
          "module": "AndroidSlidingUpPanel",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "com.makeramen",
          "module": "roundedimageview",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "pointclick-sdk-offerwall-test-1.1.07.aar",
          "url": "pointclick-sdk-offerwall-test-1.1.07.aar",
          "size": 2633203,
          "sha512": "25b90451f15798ea37ad62b00a4aafa0527c736c39b526db88bfd89998a143cec3fb95efbe80fb3488d650d693e6ba6abe0feb10f566afbaa4fccc6bf04ebd0a",
          "sha256": "1cef75f4190c0c362102100d1a1b20e4cfe5b7e5ef657cf94a83f255fc23fae7",
          "sha1": "9470820f6b1903319b6ac401dbe16cfc692b58ec",
          "md5": "b3fc0689fb89ca729a707e6e307d5ea0"
        }
      ]
    }
  ]
}
