{
  "formatVersion": "1.1",
  "component": {
    "group": "kr.co.pointclick.sdk.offerwall",
    "module": "pointclick-sdk-offerwall-test",
    "version": "1.1.07",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.0.2"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "pointclick-sdk-offerwall-test-1.1.07.aar",
          "url": "pointclick-sdk-offerwall-test-1.1.07.aar",
          "size": 2645893,
          "sha512": "abb9a9767cb4ba421d6a3736998352b748c61a965558d2aa8a5c4e70d2004dae01058f0f3e22cd3e2c7877ff4f3d0655f14a5eb3f1dec151cea62fc2ce352049",
          "sha256": "3326e2a097dd202b0fe998fd74ddf52f23c598b240c5ff223635bb42976640d9",
          "sha1": "84f253929e8f70f1bd98ee7b3b37ddb41fe0eee8",
          "md5": "a77b18463e9419b0b5fdbd8d939f7e6b"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.0.4"
          }
        },
        {
          "group": "androidx.swiperefreshlayout",
          "module": "swiperefreshlayout",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxandroid",
          "version": {
            "requires": "2.1.1"
          }
        },
        {
          "group": "io.reactivex.rxjava2",
          "module": "rxjava",
          "version": {
            "requires": "2.2.21"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "com.jakewharton.rxbinding2",
          "module": "rxbinding-recyclerview-v7",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview-selection",
          "version": {
            "requires": "1.1.0-rc03"
          }
        },
        {
          "group": "androidx.cardview",
          "module": "cardview",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.picasso",
          "module": "picasso",
          "version": {
            "requires": "2.71828"
          }
        },
        {
          "group": "com.jakewharton",
          "module": "butterknife",
          "version": {
            "requires": "10.2.3"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "retrofit",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.squareup.retrofit2",
          "module": "converter-gson",
          "version": {
            "requires": "2.5.0"
          }
        },
        {
          "group": "com.jakewharton.retrofit",
          "module": "retrofit2-rxjava2-adapter",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.okhttp3",
          "module": "logging-interceptor",
          "version": {
            "requires": "3.5.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "17.1.0"
          }
        },
        {
          "group": "com.kakao.adfit",
          "module": "ads-base",
          "version": {
            "requires": "3.21.17"
          }
        },
        {
          "group": "com.github.hannesa2",
          "module": "AndroidSlidingUpPanel",
          "version": {
            "requires": "4.7.1"
          }
        },
        {
          "group": "com.makeramen",
          "module": "roundedimageview",
          "version": {
            "requires": "2.3.0"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        },
        {
          "group": "androidx.test.espresso",
          "module": "espresso-contrib",
          "version": {
            "requires": "3.2.0"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "adquality-sdk",
          "version": {
            "requires": "7.26.2"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "applovin-adapter",
          "version": {
            "requires": "4.3.50"
          }
        },
        {
          "group": "com.applovin",
          "module": "applovin-sdk",
          "version": {
            "requires": "13.1.0"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "fyber-adapter",
          "version": {
            "requires": "4.3.37"
          }
        },
        {
          "group": "com.fyber",
          "module": "marketplace-sdk",
          "version": {
            "requires": "8.3.6"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "inmobi-adapter",
          "version": {
            "requires": "4.3.32"
          }
        },
        {
          "group": "com.inmobi.monetization",
          "module": "inmobi-ads-kotlin",
          "version": {
            "requires": "10.8.7"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "vungle-adapter",
          "version": {
            "requires": "4.3.29"
          }
        },
        {
          "group": "com.vungle",
          "module": "vungle-ads",
          "version": {
            "requires": "7.4.3"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "mintegral-adapter",
          "version": {
            "requires": "4.3.36"
          }
        },
        {
          "group": "com.mbridge.msdk.oversea",
          "module": "mbridge_android_sdk",
          "version": {
            "requires": "16.9.41"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "moloco-adapter",
          "version": {
            "requires": "4.3.12"
          }
        },
        {
          "group": "com.moloco.sdk",
          "module": "moloco-sdk",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "pangle-adapter",
          "version": {
            "requires": "4.3.35"
          }
        },
        {
          "group": "com.pangle.global",
          "module": "ads-sdk",
          "version": {
            "requires": "6.5.0.3"
          }
        },
        {
          "group": "com.unity3d.ads-mediation",
          "module": "unityads-adapter",
          "version": {
            "requires": "4.3.49"
          }
        },
        {
          "group": "com.unity3d.ads",
          "module": "unity-ads",
          "version": {
            "requires": "4.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-appset",
          "version": {
            "requires": "16.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads-identifier",
          "version": {
            "requires": "18.0.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-basement",
          "version": {
            "requires": "18.1.0"
          }
        },
        {
          "group": "androidx.databinding",
          "module": "viewbinding",
          "version": {
            "requires": "8.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "pointclick-sdk-offerwall-test-1.1.07.aar",
          "url": "pointclick-sdk-offerwall-test-1.1.07.aar",
          "size": 2645893,
          "sha512": "abb9a9767cb4ba421d6a3736998352b748c61a965558d2aa8a5c4e70d2004dae01058f0f3e22cd3e2c7877ff4f3d0655f14a5eb3f1dec151cea62fc2ce352049",
          "sha256": "3326e2a097dd202b0fe998fd74ddf52f23c598b240c5ff223635bb42976640d9",
          "sha1": "84f253929e8f70f1bd98ee7b3b37ddb41fe0eee8",
          "md5": "a77b18463e9419b0b5fdbd8d939f7e6b"
        }
      ]
    }
  ]
}
